version: '3.5'

services:
  #kratos-ui_build:
  #  build: ../
  #  container_name: 'kratos-ui_build'
  #  volumes:
  #    - dist:/usr/src/app/dist
  kratos-ui_web:
    image: nginx:alpine
    ports:
      - 80:80
    container_name: 'kratos-ui_web'
    restart: unless-stopped
    volumes:
      - dist:/www/data:ro
      - ./nginx.conf:/etc/nginx/nginx.conf

volumes:
  dist:
